ALTER TABLE "RechargeRequest" ADD COLUMN "baseAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RechargeRequest" ADD COLUMN "bonusAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RechargeRequest" ADD COLUMN "priceMier" INTEGER NOT NULL DEFAULT 0;
