ALTER TABLE "ParlayConfig" ADD COLUMN "weeklyBTicketStake" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "ParlayConfig" ADD COLUMN "weeklyBBasePool" INTEGER NOT NULL DEFAULT 12000;
ALTER TABLE "ParlayConfig" ADD COLUMN "weeklyBTicketPoolBonusBps" INTEGER NOT NULL DEFAULT 5000;
