ALTER TABLE "ParlayConfig" ADD COLUMN "smallGameWinPoints" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "ParlayConfig" ADD COLUMN "allianceGameWinPoints" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "ParlayConfig" ADD COLUMN "seriesWinPoints" INTEGER NOT NULL DEFAULT 20;
